/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as appProfileRouteImport } from './routes/(app)/profile'
import { Route as appPoliciesRouteImport } from './routes/(app)/policies'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as appContractsIndexRouteImport } from './routes/(app)/contracts.index'
import { Route as appContractsCreateRouteImport } from './routes/(app)/contracts.create'
import { Route as appContractsIdRouteImport } from './routes/(app)/contracts.$id'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appProfileRoute = appProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appRouteRoute,
} as any)
const appPoliciesRoute = appPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const appContractsIndexRoute = appContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => appRouteRoute,
} as any)
const appContractsCreateRoute = appContractsCreateRouteImport.update({
  id: '/contracts/create',
  path: '/contracts/create',
  getParentRoute: () => appRouteRoute,
} as any)
const appContractsIdRoute = appContractsIdRouteImport.update({
  id: '/contracts/$id',
  path: '/contracts/$id',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/dashboard': typeof appDashboardRoute
  '/policies': typeof appPoliciesRoute
  '/profile': typeof appProfileRoute
  '/settings': typeof appSettingsRoute
  '/contracts/$id': typeof appContractsIdRoute
  '/contracts/create': typeof appContractsCreateRoute
  '/contracts': typeof appContractsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/dashboard': typeof appDashboardRoute
  '/policies': typeof appPoliciesRoute
  '/profile': typeof appProfileRoute
  '/settings': typeof appSettingsRoute
  '/contracts/$id': typeof appContractsIdRoute
  '/contracts/create': typeof appContractsCreateRoute
  '/contracts': typeof appContractsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/not-found': typeof NotFoundRoute
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/policies': typeof appPoliciesRoute
  '/(app)/profile': typeof appProfileRoute
  '/(app)/settings': typeof appSettingsRoute
  '/(app)/contracts/$id': typeof appContractsIdRoute
  '/(app)/contracts/create': typeof appContractsCreateRoute
  '/(app)/contracts/': typeof appContractsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/not-found'
    | '/dashboard'
    | '/policies'
    | '/profile'
    | '/settings'
    | '/contracts/$id'
    | '/contracts/create'
    | '/contracts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/not-found'
    | '/dashboard'
    | '/policies'
    | '/profile'
    | '/settings'
    | '/contracts/$id'
    | '/contracts/create'
    | '/contracts'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/not-found'
    | '/(app)/dashboard'
    | '/(app)/policies'
    | '/(app)/profile'
    | '/(app)/settings'
    | '/(app)/contracts/$id'
    | '/(app)/contracts/create'
    | '/(app)/contracts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  NotFoundRoute: typeof NotFoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/policies': {
      id: '/(app)/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof appPoliciesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/contracts/': {
      id: '/(app)/contracts/'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof appContractsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/contracts/create': {
      id: '/(app)/contracts/create'
      path: '/contracts/create'
      fullPath: '/contracts/create'
      preLoaderRoute: typeof appContractsCreateRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/contracts/$id': {
      id: '/(app)/contracts/$id'
      path: '/contracts/$id'
      fullPath: '/contracts/$id'
      preLoaderRoute: typeof appContractsIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appDashboardRoute: typeof appDashboardRoute
  appPoliciesRoute: typeof appPoliciesRoute
  appProfileRoute: typeof appProfileRoute
  appSettingsRoute: typeof appSettingsRoute
  appContractsIdRoute: typeof appContractsIdRoute
  appContractsCreateRoute: typeof appContractsCreateRoute
  appContractsIndexRoute: typeof appContractsIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appDashboardRoute: appDashboardRoute,
  appPoliciesRoute: appPoliciesRoute,
  appProfileRoute: appProfileRoute,
  appSettingsRoute: appSettingsRoute,
  appContractsIdRoute: appContractsIdRoute,
  appContractsCreateRoute: appContractsCreateRoute,
  appContractsIndexRoute: appContractsIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  NotFoundRoute: NotFoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
